---
- name: deploying Redmine
  hosts:
  - app
  sudo: yes
  sudo_user: '{{ app_user }}'
  remote_user: '{{ app_user }}'

  vars:
    ruby_bin: '~/.rvm/bin/rvm default do '
    profile: '/bin/bash -lc -- '

  roles:
  - role: dresden-weekly.Rails/rails/create-release
    rails_release_id: "{{ rails_release_id_git_branch }}"
    rails_deploy_archive: "{{ redmine_deploy_archive }}"
    rails_deploy_shared_folders: "{{ redmine_deploy_shared_folders }}"

  - hicknhack-software.Redmine/config

  - role: hicknhack-software.Redmine/plugin/time_tracker
    tags:
    - plugins
    - time_tacker

  - role: hicknhack-software.Redmine/plugin/code_review
    tags:
    - plugins
    - code_review

  - role: hicknhack-software.Redmine/plugin/periodictask
    tags:
    - plugins
    - periodictask

  - role: dresden-weekly.Rails/rails/tasks/bundle
    tags:
    - finish

  - role: dresden-weekly.Rails/rails/tasks/migrate-database
    tags:
    - finish

  - hicknhack-software.Redmine/default-data

  - role: dresden-weekly.Rails/rails/update-current
    tags:
    - finish

  - role: dresden-weekly.Rails/rails/cleanup-old-releases
    tags:
    - cleanup
