
app_name: redmine
app_user: deploy
app_path: /opt/redmine

site_id: redmine
site_url_path: '/redmine'

apache_vhost_document_root: '/var/www'
site_path: '{{ apache_vhost_document_root }}{{ site_url_path }}'

git_user: '' # "{{ lookup('env', 'REPO_USER') | default('deploy', true) }}"
git_passphrase: '' # "{{ lookup('env', 'REPO_PASSWORD') | default('missing', true) }}"
git_url: "https://github.com/redmine/redmine.git"
git_branch: 2.6.2 # 2.6-stable

ruby_version: 2.1.5 # use a compatible ruby version!

# never forget to redefine the secret!
app_secret_key_base: "{{ lookup('env', 'SECRET_KEY_BASE') | default('0edf6fdcbf610f5ad59c665d15deb17af10ff7b40e8a918f928771f885cfbdec', true) }}"

db_user: redmine
db_password: redmine
db_name: redmine

redmine_admin_password: 'Ch4n53M3'

redmine_deploy_archive:
- app
- config
- config.ru
- db
- Gemfile
- lib
- public
- Rakefile
- script # Rails 3 support
- plugins # added
# no vendor!

redmine_deploy_shared_folders: # default folders that are shared between releases
- bin
- bundle
- log
- tmp
- files # added
# no public/assets

apache_server_mpm: prefork # required for SVN and Git hosting
apache_site_options:
  PassengerRuby: '{{ RUBY_BIN }}'
